# Rede Perceptron de Múltiplas Camadas
&nbsp;

**Questão 2** - Implemente uma rede perceptron de múltiplas camadas e utilize-a para aproximar as duas
funções abaixo. Em seguida, compare os resultados com as curvas exatas. No caso da letra
(b), apresente também a curva do erro médio de treinamento com relação ao número de
épocas e a curva do erro médio com o conjunto de validação.

**a)** Função lógica XOR <br>
**b)** _f(x) = sen(πx) / πx_ , 0 ≤ x ≤ 4
&nbsp;

### b) _f(x) = sen(πx) / πx_ , 0 ≤ x ≤ 4

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

In [2]:
X = []
y = []

X= np.loadtxt('data_x.txt', dtype=float, delimiter=",", encoding='bytes')
y= np.loadtxt('data_y.txt', dtype=float, delimiter=",", encoding='bytes')
print(X)

[[3.37768741 3.03181761 1.68228632 1.035667  ]
 [2.04509889 1.61973655 3.13519436 1.2132509 ]
 [1.90638782 2.33352816 3.63245154 2.01874742]
 ...
 [0.6693854  3.32148037 0.48743154 2.49159302]
 [0.6366383  3.47139372 0.9112361  0.50296671]
 [0.07111269 3.61892389 3.15467586 1.25443847]]


In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [5]:
ann = tf.keras.models.Sequential()

In [6]:
ann.add(tf.keras.layers.Dense(units=4, activation='relu'))

ann.add(tf.keras.layers.Dense(units=8, activation='relu'))


ann.add(tf.keras.layers.Dense(units=4, activation='tanh'))

In [7]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [ ]:
history= ann.fit(X_train, y_train, validation_split=0.1, epochs=1000, batch_size=32, verbose=0)

In [ ]:
y_pred = ann.predict(X_test)


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm= confusion_matrix(
    y_test.argmax(axis=1), y_pred.argmax(axis=1))
print(cm)

In [ ]:
# summarize history for accuracy
plt.figure(1)  

# summarize history for accuracy  
plt.plot(history.history['accuracy'])  
plt.plot(history.history['val_accuracy'])  
plt.title('model accuracy')  
plt.ylabel('accuracy')  
plt.xlabel('epoch')  
plt.legend(['train', 'test'], loc='upper left') 

In [ ]:
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
plt.plot(X, y, 'bo')
plt.plot(X_test, y_pred, 'go')
plt.show()